import { } from "./vars.js"
import { } from "./literals.js"
import { } from "./equals.js"
import { } from "./truethy.js"
import { } from "./obj.js"
import { } from "./functions.js"
import { } from "./import-export.js"
import { } from "./proto.js"
import { } from "./arrays.js"
import { } from "./destructuring.js"
import { } from "./spread.js"
import { } from "./chaining.js"
import { } from "./closure.js"

import { } from "./dom.js"
import { } from "./promise.js"
import { } from "./fetch.js"